name: flippra
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.8.1
  http: ^1.2.1
  get: ^4.7.2
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/
    - assets/videos/
    - assets/icons/whatsapp.png
    - assets/icons/man.png
    - assets/icons/woman.png
    - assets/icons/hindi.png
    - assets/icons/home_bg.jpg
    - assets/icons/volume.png
    - assets/icons/mute.png
    - assets/icons/banner_placeholder.png
    - assets/icons/doctor_placeholder.png
    - assets/icons/person_icon.png
    - assets/icons/profile_placeholder.png
    - assets/icons/custom_bottom_nav_frame.png
    - assets/icons/map_placeholder.png
    - assets/icons/business_card_placeholder.png
    - assets/icons/box.png
    - assets/icons/toggle.png
    - assets/icons/video_icon.png
    - assets/images/map_placeholder.png
    - assets/videos/Login_final.mp4
    - assets/videos/otp.mp4
    - assets/videos/world_map.mp4
    - assets/icons/settings.png
    - assets/icons/person.png
    - assets/icons/shopping.png
    - assets/icons/cart.png
    - assets/icons/gallery.png
    - assets/icons/top_frame.png
    - assets/icons/english.png